version: "3.9"

services:
  frontend:
    restart: unless-stopped
    
  web:
    build:
      context: ./app
      target: production
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    restart: unless-stopped
    
  db:
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=256M
