version: "3.9"

services:
  frontend:
    volumes:
      - ./frontend:/usr/share/nginx/html  # Enable hot reload for frontend
      
  web:
    build:
      context: ./app
      target: development
    volumes:
      - ./app:/app  # Enable hot reload
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: ["python", "app.py"]  # Override for development
